<?php

use Illuminate\Database\Seeder;

class LibNegaraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      // kosongkan table libkecamatan
      DB::table('libnegarapenempatans')->delete();

      // buat data berupa array untuk diinput ke database
      $libnegarapenempatans = array(
        array('id'=>1, 'kode_negara'=>'ad', 'nama_negara'=>'Andorra'),
        array('id'=>2, 'kode_negara'=>'ae', 'nama_negara'=>'United Arab Emirates'),
        array('id'=>3, 'kode_negara'=>'af', 'nama_negara'=>'Afghanistan'),
        array('id'=>4, 'kode_negara'=>'ag', 'nama_negara'=>'Antigua and Barbuda'),
        array('id'=>5, 'kode_negara'=>'ai', 'nama_negara'=>'Anguilla'),
        array('id'=>6, 'kode_negara'=>'al', 'nama_negara'=>'Albania'),
        array('id'=>7, 'kode_negara'=>'am', 'nama_negara'=>'Armenia'),
        array('id'=>8, 'kode_negara'=>'an', 'nama_negara'=>'Netherlands Antilles'),
        array('id'=>9, 'kode_negara'=>'ao', 'nama_negara'=>'Angola'),
        array('id'=>10, 'kode_negara'=>'aq', 'nama_negara'=>'Antarctica'),
        array('id'=>11, 'kode_negara'=>'ar', 'nama_negara'=>'Argentina'),
        array('id'=>12, 'kode_negara'=>'arpa', 'nama_negara'=>'Old style Arpanet'),
        array('id'=>13, 'kode_negara'=>'as', 'nama_negara'=>'American Samoa'),
        array('id'=>14, 'kode_negara'=>'at', 'nama_negara'=>'Austria'),
        array('id'=>15, 'kode_negara'=>'au', 'nama_negara'=>'Australia'),
        array('id'=>16, 'kode_negara'=>'aw', 'nama_negara'=>'Aruba'),
        array('id'=>17, 'kode_negara'=>'az', 'nama_negara'=>'Azerbaidian'),
        array('id'=>18, 'kode_negara'=>'ba', 'nama_negara'=>'Bosnia-Herzegovina'),
        array('id'=>19, 'kode_negara'=>'bb', 'nama_negara'=>'NUSA TENGGARA TIMUR'),
        array('id'=>20, 'kode_negara'=>'bd', 'nama_negara'=>'KALIMANTAN BARAT'),
        array('id'=>21, 'kode_negara'=>'be', 'nama_negara'=>'KALIMANTAN TENGAH'),
        array('id'=>22, 'kode_negara'=>'bf', 'nama_negara'=>'KALIMANTAN SELATAN'),
        array('id'=>23, 'kode_negara'=>'bg', 'nama_negara'=>'KALIMANTAN TIMUR'),
        array('id'=>24, 'kode_negara'=>'bh', 'nama_negara'=>'KALIMANTAN UTARA'),
        array('id'=>25, 'kode_negara'=>'bi', 'nama_negara'=>'SULAWESI UTARA'),
        array('id'=>26, 'kode_negara'=>'bj', 'nama_negara'=>'SULAWESI TENGAH'),
        array('id'=>27, 'kode_negara'=>'bm', 'nama_negara'=>'SULAWESI SELATAN'),
        array('id'=>28, 'kode_negara'=>'bn', 'nama_negara'=>'SULAWESI TENGGARA'),
        array('id'=>29, 'kode_negara'=>'bo', 'nama_negara'=>'GORONTALO'),
        array('id'=>30, 'kode_negara'=>'br', 'nama_negara'=>'SULAWESI BARAT'),
        array('id'=>31, 'kode_negara'=>'81', 'nama_negara'=>'MALUKU'),
        array('id'=>32, 'kode_negara'=>'82', 'nama_negara'=>'MALUKU UTARA'),
        array('id'=>33, 'kode_negara'=>'91', 'nama_negara'=>'PAPUA'),
        array('id'=>34, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>35, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>36, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>37, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>38, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>39, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>40, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>41, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>42, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>43, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>44, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>45, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>46, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>47, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>48, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>49, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>50, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>51, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>52, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>53, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>54, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>55, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>56, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>57, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>58, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>59, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>60, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>61, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>62, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>63, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>64, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>65, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>66, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>67, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>68, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>69, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>70, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>71, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>72, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>73, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>74, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>75, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>76, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>77, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>78, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>79, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>80, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>81, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>82, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>83, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>84, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>85, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>86, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>87, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>88, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>89, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>90, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>91, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>92, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>93, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>94, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>95, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>96, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>97, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>98, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>99, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>100, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>101, 'kode_negara'=>'11', 'nama_negara'=>'ACEH'),
        array('id'=>102, 'kode_negara'=>'12', 'nama_negara'=>'SUMATERA UTARA'),
        array('id'=>103, 'kode_negara'=>'13', 'nama_negara'=>'SUMATERA BARAT'),
        array('id'=>104, 'kode_negara'=>'14', 'nama_negara'=>'RIAU'),
        array('id'=>105, 'kode_negara'=>'15', 'nama_negara'=>'JAMBI'),
        array('id'=>106, 'kode_negara'=>'16', 'nama_negara'=>'SUMATERA SELATAN'),
        array('id'=>107, 'kode_negara'=>'17', 'nama_negara'=>'BENGKULU'),
        array('id'=>108, 'kode_negara'=>'18', 'nama_negara'=>'LAMPUNG'),
        array('id'=>109, 'kode_negara'=>'19', 'nama_negara'=>'KEPULAUAN BANGKA BELITUNG'),
        array('id'=>110, 'kode_negara'=>'21', 'nama_negara'=>'KEPULAUAN RIAU'),
        array('id'=>111, 'kode_negara'=>'31', 'nama_negara'=>'DKI JAKARTA'),
        array('id'=>112, 'kode_negara'=>'32', 'nama_negara'=>'JAWA BARAT'),
        array('id'=>113, 'kode_negara'=>'33', 'nama_negara'=>'JAWA TENGAH'),
        array('id'=>114, 'kode_negara'=>'34', 'nama_negara'=>'DAERAH ISTIMEWA YOGYAKARTA'),
        array('id'=>115, 'kode_negara'=>'35', 'nama_negara'=>'JAWA TIMUR'),
        array('id'=>116, 'kode_negara'=>'36', 'nama_negara'=>'BANTEN'),
        array('id'=>117, 'kode_negara'=>'51', 'nama_negara'=>'BALI'),
        array('id'=>118, 'kode_negara'=>'52', 'nama_negara'=>'NUSA TENGGARA BARAT'),
        array('id'=>119, 'kode_negara'=>'53', 'nama_negara'=>'NUSA TENGGARA TIMUR'),
        array('id'=>120, 'kode_negara'=>'61', 'nama_negara'=>'KALIMANTAN BARAT'),
        array('id'=>121, 'kode_negara'=>'62', 'nama_negara'=>'KALIMANTAN TENGAH'),
        array('id'=>122, 'kode_negara'=>'63', 'nama_negara'=>'KALIMANTAN SELATAN'),
        array('id'=>123, 'kode_negara'=>'64', 'nama_negara'=>'KALIMANTAN TIMUR'),
        array('id'=>124, 'kode_negara'=>'65', 'nama_negara'=>'KALIMANTAN UTARA'),
        array('id'=>125, 'kode_negara'=>'71', 'nama_negara'=>'SULAWESI UTARA'),
        array('id'=>126, 'kode_negara'=>'72', 'nama_negara'=>'SULAWESI TENGAH'),
        array('id'=>127, 'kode_negara'=>'73', 'nama_negara'=>'SULAWESI SELATAN'),
        array('id'=>128, 'kode_negara'=>'74', 'nama_negara'=>'SULAWESI TENGGARA'),
        array('id'=>129, 'kode_negara'=>'75', 'nama_negara'=>'GORONTALO'),
        array('id'=>130, 'kode_negara'=>'76', 'nama_negara'=>'SULAWESI BARAT'),
        array('id'=>131, 'kode_negara'=>'81', 'nama_negara'=>'MALUKU'),
        array('id'=>132, 'kode_negara'=>'82', 'nama_negara'=>'MALUKU UTARA'),
        array('id'=>133, 'kode_negara'=>'91', 'nama_negara'=>'PAPUA'),
        array('id'=>134, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>135, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>136, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>137, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>138, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>139, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>140, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>141, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>142, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>143, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>144, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>145, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>146, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>147, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>148, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>149, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>150, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>151, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>152, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>153, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>154, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>155, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>156, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>157, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>158, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>159, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>160, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>161, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>162, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>163, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>164, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>165, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>166, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>167, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>168, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>169, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>170, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>171, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>172, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>173, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>174, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>175, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>176, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>177, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>178, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>179, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>180, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>181, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>182, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>183, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>184, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>185, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>186, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>187, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>188, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>189, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>190, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>191, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>192, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>193, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>194, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>195, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>196, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>197, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>198, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>199, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>200, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>201, 'kode_negara'=>'11', 'nama_negara'=>'ACEH'),
        array('id'=>202, 'kode_negara'=>'12', 'nama_negara'=>'SUMATERA UTARA'),
        array('id'=>203, 'kode_negara'=>'13', 'nama_negara'=>'SUMATERA BARAT'),
        array('id'=>204, 'kode_negara'=>'14', 'nama_negara'=>'RIAU'),
        array('id'=>205, 'kode_negara'=>'15', 'nama_negara'=>'JAMBI'),
        array('id'=>206, 'kode_negara'=>'16', 'nama_negara'=>'SUMATERA SELATAN'),
        array('id'=>207, 'kode_negara'=>'17', 'nama_negara'=>'BENGKULU'),
        array('id'=>208, 'kode_negara'=>'18', 'nama_negara'=>'LAMPUNG'),
        array('id'=>209, 'kode_negara'=>'19', 'nama_negara'=>'KEPULAUAN BANGKA BELITUNG'),
        array('id'=>210, 'kode_negara'=>'21', 'nama_negara'=>'KEPULAUAN RIAU'),
        array('id'=>211, 'kode_negara'=>'31', 'nama_negara'=>'DKI JAKARTA'),
        array('id'=>212, 'kode_negara'=>'32', 'nama_negara'=>'JAWA BARAT'),
        array('id'=>213, 'kode_negara'=>'33', 'nama_negara'=>'JAWA TENGAH'),
        array('id'=>214, 'kode_negara'=>'34', 'nama_negara'=>'DAERAH ISTIMEWA YOGYAKARTA'),
        array('id'=>215, 'kode_negara'=>'35', 'nama_negara'=>'JAWA TIMUR'),
        array('id'=>216, 'kode_negara'=>'36', 'nama_negara'=>'BANTEN'),
        array('id'=>217, 'kode_negara'=>'51', 'nama_negara'=>'BALI'),
        array('id'=>218, 'kode_negara'=>'52', 'nama_negara'=>'NUSA TENGGARA BARAT'),
        array('id'=>219, 'kode_negara'=>'53', 'nama_negara'=>'NUSA TENGGARA TIMUR'),
        array('id'=>220, 'kode_negara'=>'61', 'nama_negara'=>'KALIMANTAN BARAT'),
        array('id'=>221, 'kode_negara'=>'62', 'nama_negara'=>'KALIMANTAN TENGAH'),
        array('id'=>222, 'kode_negara'=>'63', 'nama_negara'=>'KALIMANTAN SELATAN'),
        array('id'=>223, 'kode_negara'=>'64', 'nama_negara'=>'KALIMANTAN TIMUR'),
        array('id'=>224, 'kode_negara'=>'65', 'nama_negara'=>'KALIMANTAN UTARA'),
        array('id'=>225, 'kode_negara'=>'71', 'nama_negara'=>'SULAWESI UTARA'),
        array('id'=>226, 'kode_negara'=>'72', 'nama_negara'=>'SULAWESI TENGAH'),
        array('id'=>227, 'kode_negara'=>'73', 'nama_negara'=>'SULAWESI SELATAN'),
        array('id'=>228, 'kode_negara'=>'74', 'nama_negara'=>'SULAWESI TENGGARA'),
        array('id'=>229, 'kode_negara'=>'75', 'nama_negara'=>'GORONTALO'),
        array('id'=>230, 'kode_negara'=>'76', 'nama_negara'=>'SULAWESI BARAT'),
        array('id'=>231, 'kode_negara'=>'81', 'nama_negara'=>'MALUKU'),
        array('id'=>232, 'kode_negara'=>'82', 'nama_negara'=>'MALUKU UTARA'),
        array('id'=>233, 'kode_negara'=>'91', 'nama_negara'=>'PAPUA'),
        array('id'=>234, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>235, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>236, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>237, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>238, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>239, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>240, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>241, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>242, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>243, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>244, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>245, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>246, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>247, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>248, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>249, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>250, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>251, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
        array('id'=>252, 'kode_negara'=>'92', 'nama_negara'=>'PAPUA BARAT'),
      );

      // masukkan data ke database
      DB::table('libnegarapenempatans')->insert($libnegarapenempatans);
    }
}
