<script src="http://desamembangun.web.id/assets/plugins/metrojs/metrojs.min.js"></script>
<script src='http://desamembangun.web.id/assets/plugins/fullcalendar/moment.min.js'></script>
<script src='http://desamembangun.web.id/assets/plugins/fullcalendar/fullcalendar.min.js'></script>
<script src="http://desamembangun.web.id/assets/plugins/simple-weather/jquery.simpleWeather.min.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/google-maps/markerclusterer.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="http://desamembangun.web.id/assets/plugins/google-maps/gmaps.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/charts-flot/jquery.flot.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/charts-flot/jquery.flot.animator.min.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/charts-flot/jquery.flot.resize.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/charts-flot/jquery.flot.time.min.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/charts-morris/raphael.min.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/charts-morris/morris.min.js"></script>
<script src="http://desamembangun.web.id/assets/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<script src="http://desamembangun.web.id/assets/js/calendar.js"></script>
<script src="http://desamembangun.web.id/assets/js/dashboard.js"></script>
